//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uRecipes.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("uRecipes.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mins.
        /// </summary>
        internal static string _mins {
            get {
                return ResourceManager.GetString("_mins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string _minutes {
            get {
                return ResourceManager.GetString("_minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serving.
        /// </summary>
        internal static string _serving {
            get {
                return ResourceManager.GetString("_serving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect device.
        /// </summary>
        internal static string device_view_button_connect {
            get {
                return ResourceManager.GetString("device_view_button_connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for your commands....
        /// </summary>
        internal static string device_view_device_message {
            get {
                return ResourceManager.GetString("device_view_device_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basics.
        /// </summary>
        internal static string device_view_tab_basics {
            get {
                return ResourceManager.GetString("device_view_tab_basics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string device_view_tab_display {
            get {
                return ResourceManager.GetString("device_view_tab_display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface.
        /// </summary>
        internal static string device_view_tab_surface {
            get {
                return ResourceManager.GetString("device_view_tab_surface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here, you can adjust setting of your uCuisine device..
        /// </summary>
        internal static string deviceDefaultMessage {
            get {
                return ResourceManager.GetString("deviceDefaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are we going to cook today?.
        /// </summary>
        internal static string exploreDeafaultMessage {
            get {
                return ResourceManager.GetString("exploreDeafaultMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string exploreGreating0 {
            get {
                return ResourceManager.GetString("exploreGreating0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for recipes.
        /// </summary>
        internal static string exploreSearchPlaceHolder {
            get {
                return ResourceManager.GetString("exploreSearchPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specially for You:.
        /// </summary>
        internal static string exploreSpecially {
            get {
                return ResourceManager.GetString("exploreSpecially", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trending recipes:.
        /// </summary>
        internal static string exploreTrending {
            get {
                return ResourceManager.GetString("exploreTrending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        internal static string filters {
            get {
                return ResourceManager.GetString("filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string settings_view_label_contact {
            get {
                return ResourceManager.GetString("settings_view_label_contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display mode.
        /// </summary>
        internal static string settings_view_label_display_mode {
            get {
                return ResourceManager.GetString("settings_view_label_display_mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string settings_view_label_email {
            get {
                return ResourceManager.GetString("settings_view_label_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string settings_view_label_language {
            get {
                return ResourceManager.GetString("settings_view_label_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string settings_view_label_notification {
            get {
                return ResourceManager.GetString("settings_view_label_notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy.
        /// </summary>
        internal static string settings_view_label_privacy {
            get {
                return ResourceManager.GetString("settings_view_label_privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick User Guide.
        /// </summary>
        internal static string settings_view_label_quick_user_guide {
            get {
                return ResourceManager.GetString("settings_view_label_quick_user_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        internal static string settings_view_label_security {
            get {
                return ResourceManager.GetString("settings_view_label_security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms Of Service.
        /// </summary>
        internal static string settings_view_label_terms_of_service {
            get {
                return ResourceManager.GetString("settings_view_label_terms_of_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test size.
        /// </summary>
        internal static string settings_view_label_text_size {
            get {
                return ResourceManager.GetString("settings_view_label_text_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick User Guide.
        /// </summary>
        internal static string settings_view_label_user_guide {
            get {
                return ResourceManager.GetString("settings_view_label_user_guide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        internal static string viewAll {
            get {
                return ResourceManager.GetString("viewAll", resourceCulture);
            }
        }
    }
}
